name: Saheli
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  audioplayers: ^6.1.0
  just_audio: ^0.9.36
  record: ^5.0.4
  android_physical_buttons: ^0.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_database: ^10.4.0
  introduction_screen: ^3.1.12
  cupertino_onboarding: any
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  permission_handler: ^10.0.2
  contacts_service: ^0.6.3
  sqflite: ^2.2.0+3
  equatable: ^2.0.5
  background_sms: ^0.0.4
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  image_picker: ^0.8.6+1
  webview_flutter: ^3.0.4
  carousel_slider: ^4.1.1
  flutter_svg: ^2.0.9
  uuid: ^3.0.7
  firebase_storage: ^11.0.11
  cached_network_image: ^3.2.3
  flutter_phone_direct_caller: ^2.1.1
  shimmer: ^2.0.0
  shake: ^2.2.0
  share: ^2.0.4
  google_fonts: ^4.0.3
  sensors_plus: any
  dropdown_button2: ^2.3.9
  get: ^4.6.6
  url_launcher: ^6.1.5
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  flutter_background_service_ios: ^2.4.0
  sn_progress_dialog: ^1.1.4
  rflutter_alert: ^2.0.7
  google_places_autocomplete_text_field: any
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.3.0
  location: ^7.0.0
  flutter_ringtone_player: ^3.1.1
  dialog_flowtter: any
  flutter_sound: ^9.2.13
  flutter_native_splash: ^2.3.10
  camera: ^0.10.5+9
  flutter_riverpod: ^2.0.2
  fpdart: ^0.3.0
  routemaster: ^1.0.1
  dotted_border: ^2.0.0+2
  file_picker: ^5.2.1
  path_provider: ^2.0.5
  gradient_borders: ^1.0.0
  vibration: ^1.7.6
  telephony: ^0.2.0
  rolling_bottom_bar: ^0.2.2
  http: 0.13.6
  photo_view: ^0.14.0
  google_sign_in: any
  sign_in_button: any
  flutter_dotenv: any
  google_nav_bar: any
  line_awesome_flutter: any
  flutter_spinkit: any
  flutter_animate: any
  page_transition: any
  chat_bubbles: any
  flutter_blue_plus: ^1.32.4
  lottie: any
  google_places_flutter: any
  map_autocomplete_field: any
  flutter_polyline_points: any
  fl_country_code_picker: ^0.1.9+1
  icons_plus: ^5.0.0
  awesome_snackbar_content: ^0.1.3
  pinput: ^4.0.0
  flutter_config:
  loading_animation_widget: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  modal_bottom_sheet: ^3.0.0
  flutter_toggle_tab: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/images/logo.png"
  image_path_android: "lib/assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: font
      fonts:
        - asset: lib/assets/fonts/font.ttf
